### ISSUE TITLE
Can't build storybook

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-react#8]
After I migrated code from the monorepo I seem to have broken storybook:

```
npm run storybook

.....

99% done plugins webpack-hot-middlewarewebpack built preview 6202fbf01731110f1434 in 16375ms
ModuleParseError: Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
> import "/Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/core-js/modules/es.object.keys.js";
| import "/Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/core-js/modules/es.symbol.js";
| import "/Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/core-js/modules/es.array.filter.js";
    at handleParseError (/Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/webpack/lib/NormalModule.js:969:19)
    at /Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/webpack/lib/NormalModule.js:1088:5
    at processResult (/Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/webpack/lib/NormalModule.js:793:11)
    at /Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/webpack/lib/NormalModule.js:853:5
    at /Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/loader-runner/lib/LoaderRunner.js:406:3
    at iterateNormalLoaders (/Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/loader-runner/lib/LoaderRunner.js:232:10)
    at iterateNormalLoaders (/Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/loader-runner/lib/LoaderRunner.js:239:10)
    at /Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/loader-runner/lib/LoaderRunner.js:254:3
    at context.callback (/Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/babel-loader/lib/index.js:59:71
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
ModuleParseError: Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
> import '@storybook/react';
    at handleParseError (/Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/webpack/lib/NormalModule.js:969:19)
    at /Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/webpack/lib/NormalModule.js:1088:5
    at processResult (/Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/webpack/lib/NormalModule.js:793:11)
    at /Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/webpack/lib/NormalModule.js:853:5
    at /Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/loader-runner/lib/LoaderRunner.js:406:3
    at iterateNormalLoaders (/Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/loader-runner/lib/LoaderRunner.js:232:10)
    at iterateNormalLoaders (/Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/loader-runner/lib/LoaderRunner.js:239:10)
    at /Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/loader-runner/lib/LoaderRunner.js:254:3
    at context.callback (/Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/Aslak.Hellesoy/git/cucumber/cucumber-react/node_modules/babel-loader/lib/index.js:59:71
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**Comment by davidjgoss** [comment]
This is resolved by removing ESM-related hints from the package.json, which seemed to be confusing babel.

**Comment by davidjgoss** [comment]
(Don’t have permissions to push yet.)

**Comment by aslakhellesoy** [comment]
@davidjgoss sorry had forgotten to set that up. Should be ok now.
